name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build user-service
        run: mvn -f user-service/pom.xml clean verify

      - name: Run Sonar
        run: mvn -f user-service/pom.xml sonar:sonar \
          -Dsonar.projectKey=lokeshbohra7500_BookInn \
          -Dsonar.organization=lokeshbohra7500 \
          -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
